spring:
  profiles:
    active: develop,security
  security:
    password:
      pattern: "^(?=.*[a-z]|[A-Z]|[а-я]|[А-я])(?=.*\\d)[A-Za-zа-яА-Я\\d-+%().,:;?!*<>@{}$#_/\\[\\]\\\\]{8,}"
      description: "Пароль должен содержать в себе минимум 8 символов, русские или латинские буквы и цифры"
---
spring:
  profiles: develop
  datasource:
#    uncomment this at first start
#    initialization-mode: always
    url:  jdbc:postgresql://localhost:5432/security_demo
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      connection-timeout: 3000
      connection-test-query: SELECT 1
      pool-name: security_demo
    schema: 'classpath:/database/schema.sql'
    data: 'classpath:/database/data.sql'
  #https://stackoverflow.com/questions/4588755/disabling-contextual-lob-creation-as-createclob-method-threw-error
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    generate-ddl: true
    show-sql: true
---
spring:
  profiles: test
  datasource:
    url:  jdbc:h2:file:./test_db/security_demo
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
---
spring:
  profiles: security
security:
  oauth2:
    resource:
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      prefer-token-info: true
    client:
      client-id: ${OAUTH2_CLIENT_ID}
      client-secret: ${OAUTH2_CLIENT_SECRET}
      user-authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
      access-token-uri: https://www.googleapis.com/oauth2/v4/token
      scope: openid,email,profile
      client-authentication-scheme: form
---
spring:
  profiles: ssl
server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: ashevtsov